site_name: GeoKrige documentation (v1.0.0)
repo_url: https://github.com/pdGruby/geokrige

nav:
  - Welcome to GeoKrige: index.md
  - How to start?:
      - Installation: installation.md
      - Start Guide to GeoKrige: getting_started.md
  - Built-in Variogram Models: built-in_variogram_models.md
  - GeoKrige Classes:
      - OrdinaryKriging, SimpleKriging, UniversalKriging: kriging_classes_description.md
      - VariogramModel: variogram_model_class_description.md
      - TransformerGDF: transformer_gdf_class_description.md
      - TransformerRasterio: transformer_rasterio_class_description.md
  - Tutorials:
      - Using GeoKrige with GeoPandas: using_geokrige_with_geopandas.md
      - Using GeoKrige with rasterio: using_geokrige_with_rasterio.md
      - Creating custom variogram models: creating_custom_variogram_models.md
      - Fixing parameters of a variogram model: fixing_parameters_variogram_model.md
      - Multidimensional Kriging: multidimensional_kriging.md

theme:
  name: material
  font:
    text: Open Sans

  features:
    - content.code.copy
    - tabs: true
    - navigation.footer

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: grey

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kamil-grala-77a556300/

extra_css:
  - style.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js